### ISSUE TITLE
It'd be nice if this could work with oculus meta quest 2

### ISSUE THREAD

**Issue by Sequential-circuits** [unitreerobotics/avp_teleoperate#1]
It'd be nice if this could work with oculus meta quest 2

It is a much more widespread VR platform than Apple's

**Comment by bethalageetachandraraju** [comment]
for meta quest 2 it dents have depth perception and hand tracking feature it not available, Its the problem with hardware.

**Comment by dariooo512** [comment]
@bethalageetachandraraju what about Meta Quest 3?

**Comment by bethalageetachandraraju** [comment]
it works with meta quest 3 and vision pro

**Comment by silencht** [comment]
> @bethalageetachandraraju what about Meta Quest 3?

maybe you can refer to https://github.com/OpenTeleVision/TeleVision?tab=readme-ov-file#local-streaming
