### ISSUE TITLE
Cannot understand the control commands in the training dataset.

### ISSUE THREAD

**Issue by wwccww** [unitreerobotics/avp_teleoperate#10]
The dataset at the link provided does not clarify the meaning of "cmd" (198 dimensions?), making it difficult to perform real machine data collection.[https://drive.google.com/drive/folders/11WO96mUMjmxRo9Hpvm4ADz7THuuGNEMY?usp=sharing.]Additionally, it is difficult to understand the order of data such as qpos, pvel, and joint_pos in the dataset.

**Comment by silencht** [comment]
Please refer to this website:
https://github.com/OpenTeleVision/TeleVision/blob/main/scripts/post_process.py
