### ISSUE TITLE
Arm Movement Issue in Teleoperation Using H1 Robot: Hand Moves but Arms Remain Stationary

### ISSUE THREAD

**Issue by jluuser** [unitreerobotics/avp_teleoperate#17]
Hi, I am using the H1 robot for teleoperation, and I have encountered an issue. While the hand can follow the desired movements, the arms remain stationary and do not move at all.

I have already checked the following:

1.The motor commands for sol_q and tau_ff generated by the inverse kinematics solver are correct.
2.The computed values are properly passed to the corresponding motor control commands.

Despite this, the arm motors do not react. Could this be due to a configuration issue, missing initialization for the arm motors, or something else in the control pipeline? Any guidance on debugging this issue or common pitfalls would be greatly appreciated.

**Comment by silencht** [comment]
Do you have Debug mode (L2+R2) turned on before the control starts?

Another reason maybe is that your motor position commands are not publishing correctly through dds.
The [control file dds for the H1 branch](https://github.com/unitreerobotics/avp_teleoperate/blob/h1/teleop/robot_control/robot_arm.py) is not fully adapted, so for now you need to adapt it yourself to unitree_go idl. unitree_hg is for H1_2 and G1, while unitree_go idl is for go2 and H1. 

You can refer websites: 
- [unitree_dds_wrapper => example/h1_pub_cmd.py and h1_sub_state.py](https://github.com/unitreerobotics/unitree_dds_wrapper/blob/main/python/examples/h1_pub_cmd.py)
- [unitree_sdk2_python => example/h1_low_level_example.py](https://github.com/unitreerobotics/unitree_sdk2_python/blob/master/example/h1/low_level/h1_low_level_example.py)
