### ISSUE TITLE
Inquiry on Controlling Additional Wrist Motors with H1 Robot in Teleoperation Mode

### ISSUE THREAD

**Issue by jluuser** [unitreerobotics/avp_teleoperate#18]
Hello,

I am currently working on a teleoperation project using the Unitree H1 robot. So far, I have successfully implemented control for the robot’s Inspire Hand and arm motors. However, I now want to extend the functionality to control additional wrist motors that have been externally mounted on the robot.

I have the following questions:

1. Does the current teleoperation system for the H1 robot natively support controlling such externally added wrist motors?
2. If not, could you suggest any modifications or integrations to enable this functionality within the existing framework?
3. Are there specific topics, DDS configurations, or code files I should focus on to achieve this?

Your guidance would be greatly appreciated. Thank you for your excellent work on this project!

**Comment by silencht** [comment]
> 1.Does the current teleoperation system for the H1 robot natively support controlling such externally added wrist motors?

As far as I know, the number of motors set in the DDS message type for H1 is 20 (refer to [website1](https://github.com/unitreerobotics/unitree_sdk2_python/blob/c52f48b0b55f29dbc6ed3f67303bbd25732dc069/unitree_sdk2py/idl/unitree_go/msg/dds_/_LowCmd_.py#L31) and [website2](https://support.unitree.com/home/en/H1_developer/Joint_motor_sequence)), with no available idle motors. 

Therefore, it might be somewhat difficult to directly use the official DDS communication to control additional wrist motors.

> 2.If not, could you suggest any modifications or integrations to enable this functionality within the existing framework?
3.Are there specific topics, DDS configurations, or code files I should focus on to achieve this?

Is your motor produced by Unitree or a third-party manufacturer? Additionally, is your goal to increase the degrees of freedom of H1's arm to achieve better operational flexibility for teleoperation?
If you intend to modify the H1 into a 7-DOF robotic arm similar to the H1_2, you will also need to update its URDF to adapt to inverse kinematics solving. 

Regarding the control of additional motors, you might consider manually writing a program on H1's user computing unit to subscribe to control commands and publish motor states. Then, under the teleoperation project, you can write another program to publish control commands and subscribe to motor states (just like what the [robot_control/robot_arm.py](https://github.com/unitreerobotics/avp_teleoperate/blob/h1/teleop/robot_control/robot_arm.py) file does.).

Perhaps you can first contact our technical support team to check if there have been similar cases for reference.
