### ISSUE TITLE
AVP Teleoperation for H1

### ISSUE THREAD

**Issue by RiccardoZuppetti** [unitreerobotics/avp_teleoperate#20]
As per title I would like to try to teleoperate the H1 robot (not H1_2) using the vision pro. I should mention that I also own the inspire hands. From the G1 branch I see that everything related to H1 is still in progress, although only H1 is mentioned there and not H1 + inspire hands (like the H1_2 + inspire). Would it be possible to find out, perhaps by drawing up a list of things to do, how to adapt everything so that teleoperation is possible with H1 and H1 + inspire hands?

I would just like to understand where to concentrate my efforts so that the type of humanoid in my possession can also be teleoperated.

**Comment by silencht** [comment]
Perhaps you can refer to some of the content in the g1 branch. The g1 branch has a clearer modular distinction of functionalities. The adaptation and documentation for other types of robots will still require some time.
