### ISSUE TITLE
Time synchronization issues

### ISSUE THREAD

**Issue by lihua123456** [unitreerobotics/avp_teleoperate#22]
Hello, thank you very much for sharing your work. When saving data, I found that the timestamp was not stored in the code. How do you ensure time synchronization for the camera and robot joint data?

**Comment by silencht** [comment]
Unfortunately, we did not place much emphasis on the synchronization of timestamps.

The current synchronization relies on the execution order of [the code logic during data recording](https://github.com/unitreerobotics/avp_teleoperate/blob/0b598c115306c6ad6a1ce588799ce32dc628999f/teleop/teleop_hand_and_arm.py#L149-L234). The process is as follows: the image server sequentially reads image frames from each camera at a frequency of 30Hz, stitches them together, and publishes them. The main program subscribes to the image frames, reads the current actions and states, and packages them for recording.

If you wish to gain more experience in time synchronization, perhaps you can refer to the relevant content of the [Universal Manipulation Interface: In-The-Wild Robot Teaching Without In-The-Wild Robots](https://arxiv.org/html/2402.10329v3#S3.F5).

We also welcome your valuable suggestions :)
