### ISSUE TITLE
AVP teleoperation for g1

### ISSUE THREAD

**Issue by Baojch** [unitreerobotics/avp_teleoperate#23]
The  **2.3 Test Environment** section in the g1 branch seems to have some issues due to function modification. I suspect it might be related to the recent update. Could you please help review and address these? Thank you!

**Comment by Baojch** [comment]
In order to run the test file, I add false in teleop_test_gym.py:219
`tv_wrapper = TeleVisionWrapper(False, img_shape, img_shm.name)`
and put ` ChannelFactoryInitialize(0)` out of `if-else` in teleop/robot_control/robot_hand_unitree.py.

But still has "[Dex3_1_Controller] Waiting to subscribe dds". Whether it means that I should connect to the real G1 robot?

**Comment by silencht** [comment]
This issue is a duplicate of #15. Please follow and track progress there.

**Comment by dy-liang** [comment]
> 为了运行测试文件，我在 teleop_test_gym.py:219 中添加 false `tv_wrapper = TeleVisionWrapper(False, img_shape, img_shm.name)` 并在 teleop/robot_control/robot_hand_unitree.py` ChannelFactoryInitialize(0)`中将其删除。`if-else`
> 
> 但是仍然显示“[Dex3_1_Controller] 等待订阅 dds”。这是否意味着我应该连接到真正的 G1 机器人？
我也遇到同样问题“[Dex3_1_Controller] Waiting to subscribe dds...”，请问后续是如何解决的？是不是还有额外的配置呢？
