### ISSUE TITLE
Dark vision

### ISSUE THREAD

**Issue by muxum** [unitreerobotics/avp_teleoperate#24]
Although UI interface loaded, my vision is dark and Terminal alerting "[Dex3_1_Controller] Waiting to subscribe dds..." when I am running teleop_test_gym.py
Is that normal?
![截图 2024-12-23 18-46-58](https://github.com/user-attachments/assets/5f5cd5be-ac1e-4abd-967e-65e3077e2b1a)

**Comment by silencht** [comment]
This issue is a duplicate of #15. Please follow and track progress there.

**Comment by dy-liang** [comment]
> 虽然UI界面已经加载，但是运行teleop_test_gym.py的时候，视野一片漆黑，终端提示“[Dex3_1_Controller] 等待订阅dds...”， 请问正常吗？ ![截图 2024-12-23 18-46-58](https://github.com/user-attachments/assets/5f5cd5be-ac1e-4abd-967e-65e3077e2b1a)

I also encountered the same issue "[Dex3_1_Controller] waiting to subscribe dds...". Could you please tell me how it was resolved later? Was there any additional configuration needed?

**Comment by muxum** [comment]
try other branches, I tried h1 and it works.



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 11, 2025 20:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [unitreerobotics/avp_teleoperate] Dark vision (Issue #24)


dy-liang left a comment (unitreerobotics/avp_teleoperate#24)
  
虽然UI界面已经加载，但是运行teleop_test_gym.py的时候，视野一片漆黑，终端提示“[Dex3_1_Controller] 等待订阅dds...”， 请问正常吗？ 2024-12-23.18-46-58.png (view on web)
  
I also encountered the same issue "[Dex3_1_Controller] waiting to subscribe dds...". Could you please tell me how it was resolved later? Was there any additional configuration needed?
