### ISSUE TITLE
Can't grasp object in isaac-gym....

### ISSUE THREAD

**Issue by CodingCatMountain** [unitreerobotics/avp_teleoperate#6]
Hi, @le-wei @silencht . Since we don't have apple-vision-pro in our lab, I used another human-hand-motion-construction-from-video pipeline to realize teleoperation, and mapping the hand motion, including finger joint angles and wrist pose to control the dexterous hand in isaac-gym as mentioned in your ``teleop_hand.py`` files. However, I found the hand can't grasp the red cube. Could you give me some instructions about how to grasp the object in isaac-gym? 
Your sincerely,
Kacun.

**Comment by le-wei** [comment]
Hello, the example in `teleop_hand.py` is only used to test whether the environment configuration and communication are correct, and does not perform specific grasping operations.
