### ISSUE TITLE
无法打开网页

### ISSUE THREAD

**Issue by Yu-xm** [unitreerobotics/avp_teleoperate#7]
https://192.168.123.2:8012/?ws=wss://192.168.123.2:8012 网址无法在visionpro打开

**Comment by bethalageetachandraraju** [comment]
ip address should be modified to your network ip

**Comment by le-wei** [comment]
Please set the relevant IP and port number according to the [official documentation](https://support.unitree.com/home/zh/Teleoperation) and based on your own environment
