### ISSUE TITLE
Problems in controling the arms

### ISSUE THREAD

**Issue by PointsCoder** [unitreerobotics/avp_teleoperate#8]
Thanks for open-sourcing this code.

I encountered some problems when running the code. My robot setup is H1_2+Inspire hand. Now I could control the dex hand using Vision Pro. However, **the arms are not working**. 

Here is the program information:
![截图 2024-10-12 17-44-26](https://github.com/user-attachments/assets/3da3ff7e-0ab4-443f-8b5b-793e135ad115)

Running `cyclonedds ps`:
![image](https://github.com/user-attachments/assets/abc9fcbb-5b1c-438b-a1e2-ba56a29e3960)

Running `cyclonedds subscribe rt/lowstate`:
![image](https://github.com/user-attachments/assets/c3620f32-4d53-4acf-93ff-ed17163a90ae)

Could you please help me with this? Thank you!

**Comment by silencht** [comment]
I found that the `mode_machine` in your subscribed `rt/lowstate` is 6 and the default value in `unitree_dds_wrapper` is 4. You can try to modify the initial value of `mode_machine` in `unitree_dds_wrapper` to 6 and test again.

FILE PATH: `unitree_dds_wrapper/python/unitree_dds_wrapper/idl/unitree_hg/msg/dds_/_LowCmd_.py`    

Change 

```python
mode_machine: types.uint8 = field(default_factory=lambda: 4)
```
 to
```python
mode_machine: types.uint8 = field(default_factory=lambda: 6)
```
