### ISSUE TITLE
Wrong direction of left arm

### ISSUE THREAD

**Issue by wangxudong1998** [unitreerobotics/avp_teleoperate#9]
I want to verify the correctness of the solution of pinocchio ik_fun function in gym, but it turns out that my left hand extends to the back of my body.
What is the reason? How to solve it?

**Comment by silencht** [comment]
Could you provide more information so that we can understand the problem in more detail.

**Comment by silencht** [comment]
Due to the lack of updates or responses for an extended period, this issue will now be closed. If further assistance is needed, please feel free to reopen it or create a new issue.
